### ISSUE TITLE
create a __VERSION__ control for beta versions before PYPI release

### ISSUE THREAD

**Issue by GaryBoone** [hildogjr/KiCost#232] opened 2018-04-03 16:21 UTC
For debugging builds between releases, it would be helpful to have a build # included in the version. That would allow us to confirm we have a new build when trying to test a new build. It would also help with responding to bugs that have already been fixed in a more recent build.

**Comment by hildogjr** [comment] 2018-04-20 12:11
Will by nice if GitHUb have some tool or way to modify the file `version.py` to something like:

     __version__ = __last_version__ + '_'+$YEAR+$MONTH+$DAY+$HOUR+$MINUTE+$SECOND

on each merged code. Or we just cold standardize this way.

**Comment by hildogjr** [comment] 2018-04-22 22:42
Other option (registering here) is create a `__release__` variable on `version.py` that could be written by `setup.py` with the commit date (when installed by `pip install -U git+...`.

**Comment by set-soft** [comment] 2021-05-25 00:42
I added some code to `setup.py` to record the git value when available.
Is quite experimental. 
Let me know your opinion @hildogjr

**Comment by hildogjr** [comment] 2021-05-27 01:32
Thanks @set-soft , I didn't known the better way to code this.

I hope use this to automatize the PyPI release procedure, not depending anymore of a manual "compile" and release.

**Comment by set-soft** [comment] 2021-05-27 11:34
The mechanism needs some adjusts. I'll see if I can make a more reliable check.

About the PyPi, I have GitHub CI/CD scripts to do it. I'll also see about it. If I forget this remind me before the next release.

BTW: I think the next release should be 1.2.0, not 1.1.5. The code has too many changes.

Another detail, the version could be managed like this: After a release the version changes one minor step. Before release the version changes again. Lets take the current version as example: you currently know that the last stable release is 1.1.4, and 1.1.5 wasn't released. Any report abou 1.1.5 is about GIT code. If the next release is 1.1.6 or 1.2.0 you'll always know that any report about 1.1.5 is about a WIP version that wasn't officially released. What do you think about it?

BTW: In my experience if you keep the regression tests working, and you add enough tests, releases can be done often without any worry. When you have a good ammount of regression tests release problems are usually trivial issues, related to specific system details or related to small release errors.

**Comment by set-soft** [comment] 2021-05-28 19:06
Ok, I added some more logic:

1. During a release we must define KICOST_RELEASE as an environment var. In this case the build will be "release".
2. Now if we run the script directly from the repo, or we install with `pip install -e .` the build will be updated running `git`, not from the `version.py` file.

As before installing with `pip install git+...` will memorize the current hash and show it as build. Same for `pip` without `-e`

**Comment by set-soft** [comment] 2021-05-28 19:16
Hi @hildogjr !

I now added the script I use to release KiBot on PyPi.

We need to test it before doing a real release. When we are ready for a release and we know the script is working you'll need to define two GitHub secrets: 

- PYPI_USERNAME
- PYPI_PASSWORD

The pipeline uses them to do the release.

**Comment by hildogjr** [comment] 2021-06-01 20:36
> BTW: I think the next release should be 1.2.0, not 1.1.5. The code has too many changes.

Yes, agree. Also with the release numbers management.

> We need to test it before doing a real release. When we are ready for a release and we know the script is working you'll need to define two GitHub secrets:

Could the script be set to https://test.pypi.org/ server before? I think @devbisme /@xesscorp have to set it. (I checked and I have no access to the repository settings).

**Comment by set-soft** [comment] 2021-06-02 14:48
> > We need to test it before doing a real release. When we are ready for a release and we know the script is working you'll need to define two GitHub secrets:
> 
> Could the script be set to https://test.pypi.org/ server before?

Sure, I added `--repository testpypi` so the next release will be uploaded to the test server. Note that this will need to tag the repository twice, but this isn't a problem, GitHub allows moving tags.

> I think @devbisme /@xesscorp have to set it. (I checked and I have no access to the repository settings).

Ok. Is @devbisme reading GitHub or you must contact him by email? Once he sets the needed secrets a release is done just using a tag named "v*". We must be careful because PyPi doesn't allow removing releases. Any mistake means doing a new release (with different number). IMHO a silly requirement, but this is how PyPi works.

**Comment by xesscorp** [comment] 2021-06-02 16:49
I'm ready to transfer ownership of this repository. I assume @hildogjr would be the most reasonable choice since he's done almost all the work for the past 3 years. I will also transfer ownership of KiCost on PyPi. Let me know what you want me to do.

**Comment by set-soft** [comment] 2021-06-02 17:27
Hi @xesscorp !

I agree @hildogjr is the best choice if you no longer have time for it. 
What we currently need is to define a couple of environment variables on GitHub, but if you prefer to give the ownership to @hildogjr you can just do it and then @hildogjr will define the variables.

For PyPi the procedure is described here: https://discuss.python.org/t/transferring-a-pypi-name-to-someone-else/7196/2
For GitHub the procedure should be this: https://docs.github.com/en/enterprise-server@3.0/github/administering-a-repository/managing-repository-settings/transferring-a-repository

**Comment by hildogjr** [comment] 2021-06-07 10:41
I am reading the procedure. I will be glad to help pushing KiCost forward. (Maybe not transfer but just adding as co-owner to have access to the configurations).

**Comment by xesscorp** [comment] 2021-06-07 15:27
I'm trying to transfer ownership to @hildojr, but I keep getting the message that the hildogjr/KiCost repo already exists. Is it possible you have to release your fork before you can accept the transfer?

**Comment by hildogjr** [comment] 2021-06-07 15:48
Possible... I had released it.

**Comment by xesscorp** [comment] 2021-06-07 15:53
OK, it's going over to you.

**Comment by hildogjr** [comment] 2021-06-09 00:53
Secrets created, @set-soft, I also have access to pypi.org and test.pypi.org.

I think we are up for first test when the release come.

**Comment by xesscorp** [comment] 2021-06-09 09:07
I made you an owner of KiCost on PyPi.

**Comment by set-soft** [comment] 2021-06-09 14:17
Hi @hildogjr  and @xesscorp !

I'm glad we are advancing on this front.
This week I'm too busy with work and taxes dead-lines, but I'll see what can we do next week.

P.D. May be I'll have some time before next week, the dead-lines seems to be relaxed.

**Comment by hildogjr** [comment] 2021-06-10 21:04
No worry, @set-soft . All we have our own jobs, i glad that KiCost took a new breath with your collaboration.

**Comment by set-soft** [comment] 2021-06-12 23:23
Hi @hildogjr !

Well, it seems to be working. You can see the PyPi test release [here](https://test.pypi.org/project/kicost/)
And a GitHub draft release [here](https://github.com/hildogjr/KiCost/releases)

They are created just tagging the repo like this:

```
$ git tag -a v1.1.5 -m "Version 1.1.5"
$ git push origin --tags
```

The `.github/workflows/release.yml` is currently configured for `draft` and `pre-release`. For a real release we should change both to false.

The `.github/workflows/python-publish.yml` is currently configured for `testpypi`. We must remove `--repository testpypi` to create a real PyPi upload.

**Comment by hildogjr** [comment] 2021-06-14 17:04
Nice! Thanks.

Also the fix that I did to just summarize the last 3 changes on PyPI description worked. I think: I can set the release configuration to main PyPI and keep working to official release soon (I will do as your explained, removing `--repository testpypi`)  .

**Comment by hildogjr** [comment] 2021-06-14 17:10
I will just reopen to discus how / we we will create a "KiCost - beta" on PyPI (updated with each new master commit/merge). What do you think @set-soft ?

**Comment by set-soft** [comment] 2021-06-14 19:17
I'm not sure about  uploading betas to PyPi.

PyPi releases are permanent and needs unique versions. Using pip to install from the repo is quite simple, people wanting to test a beta can do this.

**Comment by hildogjr** [comment] 2021-06-14 22:05
Agree. We also haven't such a huge project. Users that want the the beta, usually are familiar with `git` commands. Also, now with the configured CI/CD, the releases will be less sparse in time.

I am closing this in sack of moving on with other issues.

**Closed as completed by hildogjr** 2021-06-14 22:05 UTC
Labels: enhancement, documentation
