### ISSUE TITLE
EPC2039 not found

### ISSUE THREAD

**Issue by SteveevetS** [hildogjr/KiCost#67] opened 2017-05-15 16:02 UTC
EPC2039 exists in Digikey:
https://www.digikey.com/product-detail/en/epc/EPC2039/917-1147-1-ND/6044184
but is not found ($0.00 shown).  Windows7, KiCAD 4.0.6

**Comment by xesscorp** [comment] 2017-05-15 20:05
This problem is caused by Digi-Key's search algorithm. Searching for "EPC2039" sends you to a generalized search results page that lists categories such as components and development boards. KiCost can't currently work with that search result because it doesn't know where to go. Maybe someday it will, but not today.

The immediate fix for your problem is to create a field labeled `digikey#` for the component and then assign it a value of `917-1147-1-ND`. Then KiCost will reliably find the component page.

**Closed as completed** 2017-05-24 02:05 UTC
