### ISSUE TITLE
Documentation image broken

### ISSUE THREAD

**Issue by leoheck** [hildogjr/KiCost#414] opened 2020-06-09 19:50 UTC
https://xesscorp.github.io/KiCost/docs/_build/singlehtml/index.html

![image](https://user-images.githubusercontent.com/1277920/84193127-55755280-aa71-11ea-98b9-2ed94fcea634.png)

**Comment by leoheck** [comment] 2020-06-09 19:53
It is really easier to read if you avoid justifying text like in the last paragraph.
Also, the Markdown is not being used there and this `[Kitspace](https://kitspace.org/)` doest work as expected.

**Comment by set-soft** [comment] 2021-03-13 14:33
The repo is very incosistent about the images.

I don't know which OS are you using @hildogjr . If you are using Linux I'll suggest using symlinks to avoid multiple copies of the same image.

The current status is:
- KitSpace logo:
  - ./kicost/kitspace.png
  - ./docs/kitspace.png
- GUI capture:
  - ./gui.png
  - ./docs/gui.png
- Block diagram:
  - ./docs/block_diag.png
  
The three images are used by README.rst and README.md. I know you want to remove README.md (redundant), but the relative path for the images is different when README.rst is used in `./` and `./doc`. This can be solved using symlinks.

I managed to solve what @leoheck reports, but the cost is that README.rst is more different than README.md. And I don't like the idea of creating a third copy of the KitSpace logo.

Using symlinks isn't good for Windows users. Windows currently supports links, but I found that at least one git client doesn't. What the client does is make another copy of the file.

If symlinks are good for you I can try to create a PR to solve it.

**Comment by hildogjr** [comment] 2021-03-13 20:56
I am using Linux-Ubuntu, but I never made a revision on the user manuals... I just added few sections concomitantly with the new features.

README.md was hard coded in the past by @xesscorp/@devbisme when some change on PyPI forced to use md as rst as default file. But we never really fix by deleting one of the formats.

**Comment by leoheck** [comment] 2021-03-23 13:03
@set-soft symlinks work on windows too. They are just not the default configuration. I am not sure it is needed here since is just a matter of adjusting duplicated references to use the right and single path.

**Comment by leoheck** [comment] 2021-03-23 13:04
Ah, since images are fixed on README.md may I close this issue?

**Comment by hildogjr** [comment] 2021-03-23 15:28
I think pages and documentation still using the .rst files. We just need to check and standardize this.

**Comment by set-soft** [comment] 2021-05-28 17:59
I'm closing this issue now the on-line docs also looks ok: http://xess.com/KiCost/docs/_build/singlehtml/index.html

**Comment by set-soft** [comment] 2021-05-28 18:00
Oh! BTW, I used symlinks. Any Windows user with problems just blame @leoheck :-)

**Closed as completed by set-soft** 2021-05-28 17:59 UTC
Labels: documentation

**Comment by leoheck** [comment] 2021-05-28 18:07
Symlinks are beautiful, don't blame me if Windows sucks. I don't recommend it haha. 

However, it is possible to use symlinks on Windows nowadays, they are just not there by default.
https://www.howtogeek.com/howto/16226/complete-guide-to-symbolic-links-symlinks-on-windows-or-linux/

**Comment by set-soft** [comment] 2021-05-28 20:36
Hi @leoheck !
I used symlinks on Windows (hideous Power Shell syntax), the problem is if the git client will use them.
One of our clients did a mess in a GitLab repo where I used symlinks for KiCad footprints ...
