### ISSUE TITLE
When combining user fields, the field values are not propagated over empty fields

### ISSUE THREAD

**Issue by timoalho** [hildogjr/KiCost#337] opened 2018-10-25 09:25 UTC
Say that I have a field `Foo` in my BOM, and say that R1 and R2 are resistors which get grouped (i.e. same value,footprint etc). If the `Foo` field of R1 is `bar`, and the `Foo` field of R2 is empty (i.e. `''`), the current result in the spreadsheet is:

    R,2,: 
    R,1,: bar

Whereas I'd expect the empty value to be ignored, i.e. it should be just `bar`.

A simple fix would be changing `tools.py:330` to

    values_field = [v.get(f, '') for k,v in components_grp.items() if v.get(f, '') != '']

However, I'm not submitting this as a pull request since I'm not completely sure I've understood the use case/rationale behind the current behaviour.

Note also that when listing multiple values, the refdes seems to be broken apart by commas, I think this isn't intended?

**Comment by hildogjr** [comment] 2018-10-25 16:07
@timoalho, could you provide a BOM to quick reproduce this issue?

**Comment by timoalho** [comment] 2018-10-26 09:43
.BOM attached (had to add `.txt` to make github allow uploading it). The `Supplier` field is user defined. When running with

    kicost -i UserFieldCombining.xml  --field Supplier --no_price

the two resistors are correctly combined, but the resulting `Supplier` column in the output .xlsx contains 

    R,2: 
    R,1: foobar

whereas I'd expect it to be just `foobar`.

Note also the funny formatting of the refdes'.

[UserFieldCombining.xml.txt](https://github.com/xesscorp/KiCost/files/2518651/UserFieldCombining.xml.txt)

**Comment by timoalho** [comment] 2018-10-26 09:46
Also, unrelated, but if I run the same thing without `--no_price`, I get

    No 'manf#' and 'arrow#' field in any part: distributor '{'name': 'Arrow', 'format': {'font_color': 'white', 'bg_color': '#000000'}}' will be not scraped.
    No 'manf#' and 'digikey#' field in any part: distributor '{'name': 'Digi-Key', 'format': {'font_color': 'white', 'bg_color': '#CC0000'}}' will be not scraped.
    No 'manf#' and 'farnell#' field in any part: distributor '{'name': 'Farnell', 'format': {'font_color': 'white', 'bg_color': '#FF6600'}}' will be not scraped.
    No 'manf#' and 'mouser#' field in any part: distributor '{'name': 'Mouser', 'format': {'font_color': 'white', 'bg_color': '#004A85'}}' will be not scraped.
    No 'manf#' and 'newark#' field in any part: distributor '{'name': 'Newark', 'format': {'font_color': 'white', 'bg_color': '#A2AE06'}}' will be not scraped.
    No 'manf#' and 'rs#' field in any part: distributor '{'name': 'RS Components', 'format': {'font_color': 'white', 'bg_color': '#FF0000'}}' will be not scraped.
    No 'manf#' and 'tme#' field in any part: distributor '{'name': 'TME', 'format': {'font_color': 'white', 'bg_color': '#0C4DA1'}}' will be not scraped.
    Progress:   0%|                                         | 0/1 [00:00<?, ?part/s]Traceback (most recent call last):
      File "/usr/local/bin/kicost", line 11, in <module>
        sys.exit(main())
      File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/kicost/__main__.py", line 257, in main
    dist_list=dist_list, currency=args.currency)
      File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/kicost/kicost.py", line 192, in kicost
    dist_octopart.query_part_info(parts, distributor_dict, currency)
      File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/kicost/distributors/dist_octopart.py", line 364, in query_part_info
    part_query = {'reference': i, 'sku': sku}
    UnboundLocalError: local variable 'sku' referenced before assignment

but I guess this might be related to issue #331 , so I'm not making another issue out of this?

**Comment by hildogjr** [comment] 2019-06-15 02:54
@timoalho, I am marking as incomplete to you provide my more information use example.
Sorry be the delay but we are with developers to collaborate.

Running 

1) `kicost -wi UserFieldCombining.xml -f supplier` I get the field at the spreadsheet but the parts are grouped;
2) `kicost -wi UserFieldCombining.xml -f supplier -grp supplier` the parts are grouped but the value not propagated (this is used for behaviour of description fields);
3) I see that you are using "Supplier". It is, maybe, a synonym of "Manufacture" in your BOM. So use `kicost -wi UserFieldCombining.xml --translate_fields supplier manf`.

If it's a necessary field to be propagated, I can think in something to change the behavior rules of KiCost or add a new command. Something like `--propagate_fields`.

**Comment by mdeweerd** [comment] 2021-05-04 20:22
This issue is stalling, but I made a test case for it to understand.

I think that the user intended that the Supplier field propagates just like the manf and manf# fields when components have a value in common.

The test case shows that a custom field does not propagate.

As a custom field is not a special field, I think that is acceptable and it is only "fixable" by adding some kind of "--propagate_fields" as suggested.

So I think it is an enhancement.  In case that is implemented, the testcase can be updated to refer to the new option.

**Closed as completed** 2021-05-24 20:08 UTC
Labels: bug

**Comment by set-soft** [comment] 2021-05-24 20:10
This makes sense, now we discard empty fields.

**Comment by set-soft** [comment] 2021-05-24 20:47
And I found this bug had another consequence: if you had 2 identical components and one specified the datasheet, but not the other, you didn't get a link to the datasheet in the `manf#` column. This is because the datasheet field became something like:

```
REFs:
OTHER_REFs: URL
```

Which isn't a valid URL ;-)
It made the acquire_PWM* tests to fail after patching ... but because now the output is correct.
