### ISSUE TITLE
Problem "List index out of range"

### ISSUE THREAD

**Issue by srdjanStankovic** [hildogjr/KiCost#60] opened 2017-02-11 22:24 UTC
HI,

I get a problem "List index out of range" in python.
![untitled](https://cloud.githubusercontent.com/assets/8199494/22857966/224134e2-f0b1-11e6-9655-7c0c9f5151f5.png)

**Description:**
KiCost 0.1.32
Win7 32-bit
Python 2.7

Any suggestions? Thanks

**Comment by glcerone** [comment] 2017-02-12 10:49
Hi,

I had the same problem that seems to be related to the Newark distributor, probably due to a website update. I didn't solved yet the problem but you can turn around it by using the --exclude option as follows in order to exclude the newark distributor from the search process:

kicost -i test.xml -e newark

this is not a solution but workaround the problem.

I have just opened a pull request to update kicost with the -e option that is not present in version 0.1.32. If you urgently need to produce the spreadsheet, you can download the code associated to the pull request.

best regards,

GL Cerone

**Comment by xesscorp** [comment] 2017-02-17 03:11
The latest version of KiCost (0.1.32) may have fixed this problem. Close this issue if so. Thanks.

**Comment by antIggl** [comment] 2017-02-22 12:36
The problem hasn't been fixed yet (commit 9569cd5a17e3d38cbafda402657b5ca988d9e558 ). The problem seems to be in subprocess' results parsing. I forked the repo and I ''ll have a glance on it.

**Comment by glcerone** [comment] 2017-02-22 13:31
Also for me the problem persists for Farnell and Newark distributors.

**Comment by antIggl** [comment] 2017-02-22 19:23
I ran a test for tests/test.xml, tests/test2.xml, and tests/test3.xml excluding farnell from the distributors search and it worked. Newark caused no problems for me. Could you confirm that the problem exist only for Farnell?

**Comment by xesscorp** [comment] 2017-02-23 17:04
I just uploaded a new version (0.1.33) that fixes the Farnell problem.

**Comment by Kiogora** [comment] 2017-03-02 13:15
Confirmed. Version 0.1.33 has this problem fixed. Just checked.

**Comment by antIggl** [comment] 2017-03-02 13:21
I 've just checked it too. It has been fixed on version 0.1.33.

**Closed as completed** 2017-05-24 02:06 UTC
